
CREATE TABLE USER (
dni VARCHAR() PRIMARY KEY,
name VARCHAR() NOT NULL,
surname VARCHAR() NOT NULL,
email VARCHAR() NOT NULL,
dateup LOCALTIME NOT NULL,
idRoles INTEGER NOT NULL,
FOREIGN KEY (idRoles) REFERENCES USER_ROLES(userRolesId)
);

CREATE TABLE ITEMS (
itemsId IDENTITY NOT NULL PRIMARY KEY,
description VARCHAR() NOT NULL,
price FLOAT NOT NULL,
status VARCHAR() NOT NULL,
creator VARCHAR() NOT NULL,
usermod VARCHAR() NOT NULL,
dateup LOCALTIME NOT NULL
);

CREATE TABLE PRICE_REDUCTION (
priceReductionId IDENTITY NOT NULL PRIMARY KEY,
creator VARCHAR() NOT NULL,
reducedprice FLOAT NOT NULL,
datestart LOCALTIME NOT NULL,
dateend LOCALTIME NOT NULL,
idItems IDENTITY,
FOREIGN KEY (idItems) REFERENCES ITEMS(itemsId)
);

CREATE TABLE VENDOR {
vendorId IDENTITY NOT NULL PRIMARY KEY,
name VARCHAR() NOT NULL,
country VARCHAR() NOT NULL,
description VARCHAR() NOT NULL
}

CREATE TABLE ITEMS_VENDOR {
itemsVendorId IDENTITY NOT NULL PRIMARY KEY,
idItems IDENTITY NOT NULL,
idVendor IDENTITY NOT NULL,
FOREIGN KEY (idItems) REFERENCES ITEMS(itemsId),
FOREIGN KEY (idVendor) REFERENCES VENDOR(vendorId)
}

CREATE TABLE USER_ROLES{
userRolesId INTEGER NOT NULL PRIMARY KEY,
name VARCHAR() NOT NULL
}

INSERT INTO USER
(dni,name,surname,email,dateup) VALUES
('45939593Z','PEPE','Gonzales','PEPE@Gonzales.com','2020-05-12'),
('35676534X','ANTONIO','Perez','ANTONIO@Perez.com','2020-06-12');

INSERT INTO ITEMS
(description,price,status,creator,usermod,dateup) VALUES
('Caja',3.65,'ACTIVE','PEPE',null,'2020-09-25'),
('Cojin',9.26,'INACTIVE','PEPE',null,'2020-12-14'),
('Silla',20.75,'ACTIVE','PEPE',null,'2020-04-08'),

INSERT INTO PRICE_REDUCTION
(creator,reducedprice,datestart,dateend) VALUES
('PEPE',1.25,'2021-04-09','2021-04-17'),
('PEPE',2,'2021-04-10','2021-10-01');


INSERT INTO VENDOR
(name,country,description) VALUES
('Maderas Experss','Spain','Proveedor de madera'),
('Philips','Países Bajos','Bombillas led');

INSERT INTO ITEMS_VENDOR VALUES
(1,1),
(2,1);
